/*****************************************************************************
 *                        Shapeways, Inc Copyright (c) 2011
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 ****************************************************************************/

package abfab3d.transforms;

import java.util.Vector;

import javax.vecmath.Matrix3d;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector4d;
import javax.vecmath.Matrix4d;
import javax.vecmath.AxisAngle4d;

import abfab3d.util.Vec;
import abfab3d.util.Initializable;
import abfab3d.util.Symmetry;
import abfab3d.util.ReflectionGroup;
import abfab3d.util.VecTransform;

import net.jafama.FastMath;

import static abfab3d.util.Output.printf;
import static abfab3d.util.Symmetry.getReflection;
import static abfab3d.util.Symmetry.toFundamentalDomain;



/**
   makes transformations for symmetry groups generated by reflections
*/
public class ReflectionSymmetry  implements VecTransform, Initializable  {
    
    
    ReflectionGroup group;
    double riemannSphereRadius;
    
    public ReflectionSymmetry(){            
        
    }
    
    public void setGroup(ReflectionGroup group){
        this.group = group;
    }
    
    public void setRiemannSphereRadius(double value){
        this.riemannSphereRadius = value;
    }
    
    public int initialize(){
        
        if(group == null){               
            // init to simple one generator group 
            group = new ReflectionGroup(new ReflectionGroup.SPlane[]{new ReflectionGroup.Plane(new Vector3d(1,0,0),0)});
        }
        
        group.setRiemannSphereRadius(riemannSphereRadius);
        return RESULT_OK;
    }
    
    public int transform(Vec in, Vec out) {
        // direct transform is identity transform 
        out.set(in);
        // TODO we use custom combination of reflectins from the group 
        return RESULT_OK;
        
    }
    public int inverse_transform(Vec in, Vec out) {
        out.set(in);
        return group.toFundamentalDomain(out);
        
    }
    
    
} // class ReflectionSymmetry 

