#*********************************************************************
#
#                         (C) 2007 Yumetech, Inc
#                        http://www.yumetech.com
#
# Package makefile for the udesign.io directory
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGE = udesign.soap

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
	SOAPException.java \
	SOAPFault.java \
	SOAPConstants.java \
	XMLWriter.java \
	XMLParser.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = 

include ${PROJECT_ROOT}/make/Makefile.jav
